// Generated by tools/derive-accents.mjs. Do not edit by hand.
//
// Each accent is a Material 3 dark scheme seeded from the colour Vice has
// shipped since 2.0, built with Expressive's palette chromas. The seed
// contributes its hue and nothing else: tones come from the scheme, so a card
// and an inactive button are tonal roles rather than picked values.
//
// Pair a fill with its own on-colour and nothing else. The generator checks
// every pair below at WCAG AA and refuses to write this file if one fails.

export type AccentName = 'blue' | 'purple' | 'green' | 'red' | 'orange';

export interface AccentRamp {
  /** M3 primary. Filled buttons, active toggles, the record dot. */
  base: string;
  /** Text and icons on `base`. Never use --color-text-* on a filled button. */
  onBase: string;
  hover: string;
  active: string;
  /** M3 surface. The page. */
  bg: string;
  /** Recessed controls: a select at rest, a switch that is off. */
  surfaceLowest: string;
  /** Content containers: clip cards, settings cards, panels. */
  surfaceLow: string;
  /** The sidebar and other navigation surfaces. */
  surface: string;
  surfaceHigh: string;
  surfaceHighest: string;
  onSurface: string;
  /** Dimmer body text: meta lines, secondary labels. */
  onSurfaceVariant: string;
  /** The deeper tonal rung, same hue as the accent: playlist chips. */
  primaryContainer: string;
  onPrimaryContainer: string;
  /** The tonal rung: an inactive button, a quiet control. */
  secondaryContainer: string;
  onSecondaryContainer: string;
  /** A contrasting accent. Available, currently unused: at accent+60 it lands
   * far enough away to read as a different theme leaking in. */
  tertiaryContainer: string;
  onTertiaryContainer: string;
  /** Interactive boundaries. */
  outline: string;
  /** Dividers and hairlines. */
  outlineVariant: string;
  error: string;
  onError: string;
  errorContainer: string;
  onErrorContainer: string;
  /** Drives the ambient wash. Never carries text. */
  ambient: string;
}

export const ACCENTS: Record<AccentName, AccentRamp> = {
  blue: {
    base: '#8ab9f3',
    onBase: '#003259',
    hover: '#9fcaff',
    active: '#79a9e2',
    bg: '#11131a',
    surfaceLowest: '#0c0e15',
    surfaceLow: '#191b23',
    surface: '#1d1f27',
    surfaceHigh: '#272a31',
    surfaceHighest: '#32343c',
    onSurface: '#e1e2ec',
    onSurfaceVariant: '#c2c6d6',
    primaryContainer: '#08497c',
    onPrimaryContainer: '#d2e4ff',
    secondaryContainer: '#324862',
    onSecondaryContainer: '#d2e4ff',
    tertiaryContainer: '#563c69',
    onTertiaryContainer: '#f3daff',
    outline: '#8c909f',
    outlineVariant: '#424654',
    error: '#ffb4ab',
    onError: '#690005',
    errorContainer: '#93000a',
    onErrorContainer: '#ffdad6',
    ambient: '#003660',
  },
  purple: {
    base: '#d0bcff',
    onBase: '#372463',
    hover: '#dfd0ff',
    active: '#c0abf4',
    bg: '#161219',
    surfaceLowest: '#110c14',
    surfaceLow: '#1f1a21',
    surface: '#231e25',
    surfaceHigh: '#2e2830',
    surfaceHighest: '#39333b',
    onSurface: '#eadfea',
    onSurfaceVariant: '#d0c2d3',
    primaryContainer: '#4e3b7c',
    onPrimaryContainer: '#e9ddff',
    secondaryContainer: '#4b4163',
    onSecondaryContainer: '#e9ddff',
    tertiaryContainer: '#6c3648',
    onTertiaryContainer: '#ffd9e2',
    outline: '#998d9d',
    outlineVariant: '#4d4351',
    error: '#ffb4ab',
    onError: '#690005',
    errorContainer: '#93000a',
    onErrorContainer: '#ffdad6',
    ambient: '#3c2968',
  },
  green: {
    base: '#85d7ae',
    onBase: '#003824',
    hover: '#95e8be',
    active: '#74c69e',
    bg: '#0c1513',
    surfaceLowest: '#07100e',
    surfaceLow: '#141d1b',
    surface: '#18211f',
    surfaceHigh: '#232c29',
    surfaceHighest: '#2d3734',
    onSurface: '#dbe5e0',
    onSurfaceVariant: '#b8cbc4',
    primaryContainer: '#005236',
    onPrimaryContainer: '#a0f4c9',
    secondaryContainer: '#284e3c',
    onSecondaryContainer: '#c2ecd3',
    tertiaryContainer: '#004d61',
    onTertiaryContainer: '#b9eaff',
    outline: '#83958f',
    outlineVariant: '#3a4a45',
    error: '#ffb4ab',
    onError: '#690005',
    errorContainer: '#93000a',
    onErrorContainer: '#ffdad6',
    ambient: '#003d28',
  },
  red: {
    base: '#ffb3ad',
    onBase: '#5a1b19',
    hover: '#ffcbc6',
    active: '#fd9c95',
    bg: '#1c110d',
    surfaceLowest: '#160c08',
    surfaceLow: '#251915',
    surface: '#291d19',
    surfaceHigh: '#342723',
    surfaceHighest: '#40322d',
    onSurface: '#f5ded7',
    onSurfaceVariant: '#dfc0b6',
    primaryContainer: '#77302d',
    onPrimaryContainer: '#ffdad7',
    secondaryContainer: '#663b38',
    onSecondaryContainer: '#ffdad7',
    tertiaryContainer: '#5d4202',
    onTertiaryContainer: '#ffdea6',
    outline: '#a78b81',
    outlineVariant: '#58423a',
    error: '#ffb4ab',
    onError: '#690005',
    errorContainer: '#93000a',
    onErrorContainer: '#ffdad6',
    ambient: '#5f1f1d',
  },
  orange: {
    base: '#ffb690',
    onBase: '#552100',
    hover: '#ffcdb4',
    active: '#f9a171',
    bg: '#1b120a',
    surfaceLowest: '#150c06',
    surfaceLow: '#231a11',
    surface: '#281e15',
    surfaceHigh: '#33281f',
    surfaceHighest: '#3e3329',
    onSurface: '#f2dfd1',
    onSurfaceVariant: '#dcc2ad',
    primaryContainer: '#73350e',
    onPrimaryContainer: '#ffdbca',
    secondaryContainer: '#653d27',
    onSecondaryContainer: '#ffdbca',
    tertiaryContainer: '#4d4808',
    onTertiaryContainer: '#ede596',
    outline: '#a48c7a',
    outlineVariant: '#554334',
    error: '#ffb4ab',
    onError: '#690005',
    errorContainer: '#93000a',
    onErrorContainer: '#ffdad6',
    ambient: '#5b2400',
  },
};

export const DEFAULT_ACCENT: AccentName = 'blue';

export const ACCENT_NAMES = Object.keys(ACCENTS) as AccentName[];
